create table if not exists public.quote_requests (
    id uuid primary key default gen_random_uuid(),
    reference_code text not null unique,
    channel text not null check (channel in ('email', 'whatsapp')),
    status text not null default 'new' check (status in ('new', 'reviewing', 'quoted', 'approved', 'fulfilled', 'closed')),
    name text not null,
    company text,
    email text not null,
    phone text,
    quantity text,
    delivery_location text,
    required_timeline text,
    specifications text,
    products jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.quote_requests enable row level security;

create policy "Allow anonymous quote creation"
    on public.quote_requests
    for insert
    to anon
    with check (
        length(trim(name)) between 1 and 100
        and length(trim(email)) between 3 and 160
        and jsonb_typeof(products) = 'array'
    );

create index if not exists quote_requests_status_idx on public.quote_requests (status);
create index if not exists quote_requests_created_at_idx on public.quote_requests (created_at desc);

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text,
    role text not null default 'sales' check (role in ('admin', 'sales')),
    created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.profiles
        where id = auth.uid()
          and role in ('admin', 'sales')
    );
$$;

create policy "Staff can view profiles"
    on public.profiles
    for select
    to authenticated
    using (id = auth.uid() or public.is_staff());

create policy "Staff can view quotes"
    on public.quote_requests
    for select
    to authenticated
    using (public.is_staff());

create policy "Staff can update quotes"
    on public.quote_requests
    for update
    to authenticated
    using (public.is_staff())
    with check (public.is_staff());

create table if not exists public.cms_posts (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    title text not null,
    excerpt text not null,
    content text not null,
    image text,
    author text not null default 'Pelano Resources Ltd',
    category text not null,
    tags text[] not null default '{}',
    date date not null default current_date,
    read_time integer not null default 3 check (read_time between 1 and 60),
    status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.cms_posts enable row level security;

create policy "Public can read published posts"
    on public.cms_posts
    for select
    to anon, authenticated
    using (status = 'published' or public.is_staff());

create policy "Staff can create posts"
    on public.cms_posts
    for insert
    to authenticated
    with check (public.is_staff());

create policy "Staff can edit posts"
    on public.cms_posts
    for update
    to authenticated
    using (public.is_staff())
    with check (public.is_staff());

create table if not exists public.newsletter_subscribers (
    id uuid primary key default gen_random_uuid(),
    email text not null unique,
    consent boolean not null check (consent = true),
    consented_at timestamptz not null default now(),
    source text not null default 'website',
    status text not null default 'pending' check (status in ('pending', 'confirmed', 'unsubscribed')),
    confirmation_token_hash text,
    confirmation_expires_at timestamptz,
    unsubscribe_token_hash text,
    confirmed_at timestamptz,
    unsubscribed_at timestamptz,
    created_at timestamptz not null default now()
);

alter table public.newsletter_subscribers
    add column if not exists status text not null default 'pending',
    add column if not exists confirmation_token_hash text,
    add column if not exists confirmation_expires_at timestamptz,
    add column if not exists unsubscribe_token_hash text,
    add column if not exists confirmed_at timestamptz,
    add column if not exists unsubscribed_at timestamptz;

alter table public.newsletter_subscribers
    drop constraint if exists newsletter_subscribers_status_check;

alter table public.newsletter_subscribers
    add constraint newsletter_subscribers_status_check
    check (status in ('pending', 'confirmed', 'unsubscribed'));

update public.newsletter_subscribers
set status = 'pending'
where status not in ('pending', 'confirmed', 'unsubscribed');

alter table public.newsletter_subscribers enable row level security;
revoke all on public.newsletter_subscribers from public, anon, authenticated;
grant select on public.newsletter_subscribers to authenticated;

drop policy if exists "Visitors can subscribe with consent" on public.newsletter_subscribers;

revoke insert, update, delete on public.newsletter_subscribers from anon, authenticated;

drop policy if exists "Staff can view subscribers" on public.newsletter_subscribers;

create policy "Staff can view subscribers"
    on public.newsletter_subscribers
    for select
    to authenticated
    using (public.is_staff());

create index if not exists newsletter_subscribers_status_idx
    on public.newsletter_subscribers (status, created_at desc);

create table if not exists public.newsletter_request_limits (
    request_key_hash text primary key check (request_key_hash ~ '^[a-f0-9]{64}$'),
    window_started_at timestamptz not null,
    request_count integer not null check (request_count > 0),
    updated_at timestamptz not null
);

alter table public.newsletter_request_limits enable row level security;
revoke all on public.newsletter_request_limits from anon, authenticated;

create or replace function public.consume_newsletter_signup_limit(p_request_key_hash text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
    current_count integer;
    current_time timestamptz := now();
begin
    if auth.role() <> 'service_role'
       or p_request_key_hash !~ '^[a-f0-9]{64}$' then
        raise exception 'Unauthorized newsletter rate-limit request.';
    end if;

    delete from public.newsletter_request_limits
    where updated_at < current_time - interval '1 day';

    insert into public.newsletter_request_limits (request_key_hash, window_started_at, request_count, updated_at)
    values (p_request_key_hash, current_time, 1, current_time)
    on conflict (request_key_hash) do update
    set window_started_at = case
            when public.newsletter_request_limits.window_started_at < current_time - interval '15 minutes'
            then current_time
            else public.newsletter_request_limits.window_started_at
        end,
        request_count = case
            when public.newsletter_request_limits.window_started_at < current_time - interval '15 minutes'
            then 1
            else public.newsletter_request_limits.request_count + 1
        end,
        updated_at = current_time
    returning request_count into current_count;

    return current_count <= 4;
end;
$$;

revoke all on function public.consume_newsletter_signup_limit(text) from public, anon, authenticated;
grant execute on function public.consume_newsletter_signup_limit(text) to service_role;

create index if not exists cms_posts_published_date_idx on public.cms_posts (date desc) where status = 'published';

create table if not exists public.social_posts (
    id bigint generated by default as identity primary key,
    platform text not null check (platform in ('instagram', 'facebook', 'linkedin', 'youtube')),
    caption text not null,
    image_url text,
    post_url text not null,
    status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.social_posts enable row level security;

create policy "Public can view approved social posts"
    on public.social_posts
    for select
    to anon, authenticated
    using (status = 'approved' or public.is_staff());

create policy "Staff can submit social posts"
    on public.social_posts
    for insert
    to authenticated
    with check (public.is_staff());

create policy "Staff can moderate social posts"
    on public.social_posts
    for update
    to authenticated
    using (public.is_staff())
    with check (public.is_staff());
